version: '3.2'
services:
  prom-pushgateway:
    container_name: prometheus-pushgateway
    image: prom/pushgateway
    ports:
      - 9091:9091
    restart: on-failure
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus:/etc/prometheus:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
    restart: on-failure
  grafana:
    container_name: grafana
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./monitoring/grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=foobar
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: on-failure
  app:
    container_name: app
    build:
      context: app/
      dockerfile: Dockerfile
    depends_on:
      - prometheus
    ports:
      - 8080:8080
    restart: on-failure
